server:
  port: 8101
  
spring:
  application:
    name: CATALOG-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: mysqlpwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8900
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
