server:
  port: 8102
  
spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: ordersdb
      port: 27017
      host: localhost
  config:
    import: optional:configserver:http://localhost:8900
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
